sudo: required

services:
  - docker

language: c

script:
  - docker pull ubuntudesktop/gnome-3-28-1804
  - cid=`docker run --tty --detach --volume $TRAVIS_BUILD_DIR:/multipass-gui --workdir /multipass-gui ubuntudesktop/gnome-3-28-1804 bash`
  - docker exec $cid apt update
  - docker exec $cid snapcraft
  - if [ -n "$encrypted_4266e9dfa90e_key" -a "$TRAVIS_PULL_REQUEST" = false -a "$TRAVIS_BRANCH" = "master" ]; then docker exec $cid bash -c "openssl aes-256-cbc -K $encrypted_4266e9dfa90e_key -iv $encrypted_4266e9dfa90e_iv -in snap-store.key.enc -out snap-store.key -d"; fi
  - if [ -n "$encrypted_4266e9dfa90e_key" -a "$TRAVIS_PULL_REQUEST" = false -a "$TRAVIS_BRANCH" = "master" ]; then docker exec $cid bash -c "snapcraft login --with snap-store.key"; fi
  - if [ -n "$encrypted_4266e9dfa90e_key" -a "$TRAVIS_PULL_REQUEST" = false -a "$TRAVIS_BRANCH" = "master" ]; then docker exec $cid snapcraft push multipass-gui*.snap --release edge; fi
  - if [ -n "$encrypted_4266e9dfa90e_key" -a "$TRAVIS_PULL_REQUEST" = false -a "$TRAVIS_BRANCH" = "master" ]; then docker exec $cid snapcraft logout; fi
